### PR TITLE
Add NVIDIA GTX 1070 Support

### PR DESCRIPTION
**Pull request by benjaminchodroff**
Tested with Asus STRIX ROG GTX 1070

### CODE REVIEW

**Comment by jonasmalacofilho** [comment]
Does it really work with (essentially) the `RogTuring` driver?  That's great news!

Just to be sure, have you tested all documented features, including the `status --verbose` output and all of the lighting modes that are documented in the [corresponding guide](https://github.com/liquidctl/liquidctl/blob/master/docs/nvidia-guide.md#asus-strix-rtx-2080-ti-oc)?

---

_(I can manually apply your patch and fix the issues bellow myself if you're not comfortable with `git rebase`, but otherwise:)_

Can you rebase this on top of the main (currently still called `master`) branch, and edit the pull request base accordingly, so that it only contains your single patch?

Additionally, can you also rename the class to `RogPascal`, to make it uniform with the other drivers?

Finally, can you list the new device in the corresponding guide, in the man page, and in the README's list of supported devices?

**Comment by benjaminchodroff** [comment]
I tested setting the colors with rainbow, fixed, breathing, and the status works great too. I also tested with two NVIDIA STRIX settings - they both work. 

Ah, yes, I see that array now. I'll go ahead and clean this up and submit a new pull request rather than deal with the rebase, will add some docs, and submit to master. Thanks!

**Comment by jonasmalacofilho** [comment]
Thank you for the extra details.

What did you mean by "two NVIDIA STRIX settings"?

**Comment by benjaminchodroff** [comment]
I have two Asus STRIX GTX 1070's in the machine, and was pleased to see
that there were no issues with using this utility to identify and command
them independently and correctly.

**Comment by jonasmalacofilho** [comment]
Oh, that's great to hear as well. Thanks again.

**Pull request closed without merging**
