### PR TITLE
Commander Core: Add fan curve support

### PR DESCRIPTION
**Pull request by ParkerMc**
Add hardware fan curve support to the commander core.

Related: #218, #447

---

Checklist:

- [x] Adhere to the [development process]
- [x] Conform to the [style guide]
- [ ] Verify that the changes work as expected on real hardware
- [ ] Add automated tests cases
- [ ] Verify that all (other) automated tests (still) pass
- [ ] Update the README and other applicable documentation pages
- [ ] Update the `liquidctl.8` Linux/Unix/Mac OS man page
- [ ] Update or add applicable `docs/*guide.md` device guides
- [ ] Submit relevant data, scripts or dissectors to https://github.com/liquidctl/collected-device-data

New CLI flag?

- [ ] Adjust the completion scripts in `extra/completions/`

New device?

- [ ] Regenerate `extra/linux/71-liquidctl.rules` (instructions in the file header)
- [ ] Add entry to the README's supported device list with applicable notes (at least `en`)

New driver?

- [x] Document the protocol in `docs/developer/protocol/`

[development process]: https://github.com/liquidctl/liquidctl/blob/main/docs/developer/process.md
[style guide]: https://github.com/liquidctl/liquidctl/blob/main/docs/developer/style-guide.md

### CODE REVIEW

**Comment by ParkerMc** [comment]
This PR is on hold due to the firmware update that needs to be addressed before this PR can proceed.

**Comment by intelfx** [comment]
@ParkerMc is anything blocking this work besides your time/availability? The relevant protocol parts are already fully known, correct?

(not trying to poke you, just wondering if there are any obstacles to just picking it up where you left off and finishing the code)

**Comment by ParkerMc** [comment]
> @ParkerMc is anything blocking this work besides your time/availability? The relevant protocol parts are already fully known, correct?

Correct. This PR contains most of the work include documentation for the protocol needed. Nothing is blocking this at the moment other than my availability.

Here's what's left needed for this PR:
Actually put the user entered fan curve into the data (there's a to-do comment)
Write tests and documentation on how to use the command

**Comment by intelfx** [comment]
Great, I'll try to finish this up then :)

**Comment by intelfx** [comment]
Progress report: either I'm not seeing something obvious, or the fact that v2 firmware is limited to 96 bytes of response means that the `_MODE_HW_CURVE_PERCENT` command response will always be truncated and unusable. Reverting `RESPONSE_LENGTH` to 1024 doesn't seem to help.

I don't have Wireshark experience, but I'll try to get Windows onto that machine and see what the vendor driver is doing there (unless I'm missing something obvious, that is).

**Comment by ParkerMc** [comment]
> Progress report: either I'm not seeing something obvious, or the fact that v2 firmware is limited to 96 bytes of response means that the `_MODE_HW_CURVE_PERCENT` command response will always be truncated and unusable. Reverting `RESPONSE_LENGTH` to 1024 doesn't seem to help.

Yes, I remember now. v2 is limited to that. I have the solution for the write command but I haven't looked into a solution for the read command yet.

**Comment by ParkerMc** [comment]
> Yes, I remember now. v2 is limited to that. I have the solution for the write command but I haven't looked into a solution for the read command yet.

For writing the command is `0x06` then to write more it is `0x07` (from some stuff I did for openrgb a bit back [here](https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/Controllers/CorsairCommanderCoreController/CorsairCommanderCoreController.cpp#L184)

If we're lucky the "read more command" will follow the same format. Try sending a `0x09` command right after the read and see if it reads more.

**Comment by paskalll** [comment]
I can Test if you need assistance.

Have a commander core and commander xt with an h170i.

Needed to modify the match part of commander core a little bit because my core is is a core st id 😅

Would be great to use a curve with liquidctl

**Comment by Albinoman887** [comment]
any progress on this? i started playing around with it and thought i was getting somewhere until i read about the command resp length being too short and i'm now offiically lost but for what its worth heres what ive come up with so far. it fails with an index out of range error when i try to set any curve though

`"""liquidctl drivers for Corsair Commander Core.

Supported devices:

- Corsair Commander Core

Copyright ParkerMc and contributors
SPDX-License-Identifier: GPL-3.0-or-later
"""

import logging
from contextlib import contextmanager

from liquidctl.driver.usb import UsbHidDriver
from liquidctl.error import ExpectationNotMet, NotSupportedByDriver, NotSupportedByDevice
from liquidctl.util import clamp, u16le_from

_LOGGER = logging.getLogger(__name__)

_REPORT_LENGTH = 96
_RESPONSE_LENGTH = 96

_INTERFACE_NUMBER = 0

_FAN_COUNT = 6

_CMD_WAKE = (0x01, 0x03, 0x00, 0x02)
_CMD_SLEEP = (0x01, 0x03, 0x00, 0x01)
_CMD_GET_FIRMWARE = (0x02, 0x13)
_CMD_CLOSE_ENDPOINT = (0x05, 0x01, 0x00)
_CMD_OPEN_ENDPOINT = (0x0d, 0x00)
_CMD_READ = (0x08, 0x00)
_CMD_WRITE = (0x06, 0x00)

_MODE_LED_COUNT = (0x20,)
_MODE_GET_SPEEDS = (0x17,)
_MODE_GET_TEMPS = (0x21,)
_MODE_CONNECTED_SPEEDS = (0x1a,)
_MODE_HW_SPEED_MODE = (0x60, 0x6d)
_MODE_HW_FIXED_PERCENT = (0x61, 0x6d)
_MODE_HW_CURVE_PERCENT = (0x62, 0x6d)

_DATA_TYPE_SPEEDS = (0x06, 0x00)
_DATA_TYPE_LED_COUNT = (0x0f, 0x00)
_DATA_TYPE_TEMPS = (0x10, 0x00)
_DATA_TYPE_CONNECTED_SPEEDS = (0x09, 0x00)
_DATA_TYPE_HW_SPEED_MODE = (0x03, 0x00)
_DATA_TYPE_HW_FIXED_PERCENT = (0x04, 0x00)
_DATA_TYPE_HW_CURVE_PERCENT = (0x05, 0x00)

_FAN_MODE_FIXED_PERCENT = 0x00
_FAN_MODE_CURVE_PERCENT = 0x02


class CommanderCore(UsbHidDriver):
    """Corsair Commander Core"""

    _MATCHES = [
        (0x1b1c, 0x0c1c, 'Corsair Commander Core (experimental)', {"has_pump": True}),
        (0x1b1c, 0x0c2a, 'Corsair Commander Core XT (experimental)', {"has_pump": False}),
        (0x1b1c, 0x0c32, 'Corsair Commander ST (experimental)', {"has_pump": True}),
    ]

    def __init__(self, device, description, has_pump, **kwargs):
        super().__init__(device, description, **kwargs)
        self._has_pump = has_pump

    def initialize(self, **kwargs):
        """Initialize the device and get the fan modes."""

        with self._wake_device_context():
            # Get Firmware
            res = self._send_command(_CMD_GET_FIRMWARE)
            fw_version = (res[3], res[4], res[5])

            status = [('Firmware version', '{}.{}.{}'.format(*fw_version), '')]

            # Get LEDs per fan
            res = self._read_data(_MODE_LED_COUNT, _DATA_TYPE_LED_COUNT)
            num_devices = res[0]
            led_data = res[1:1 + num_devices * 4]
            for i in range(0, num_devices):
                connected = u16le_from(led_data, offset=i * 4) == 2
                num_leds = u16le_from(led_data, offset=i * 4 + 2)
                if self._has_pump:
                    label = 'AIO LED count' if i == 0 else f'RGB port {i} LED count'
                else:
                    label = f'RGB port {i+1} LED count'

                status += [(label, num_leds if connected else None, '')]

            # Get what fans are connected
            res = self._read_data(_MODE_CONNECTED_SPEEDS, _DATA_TYPE_CONNECTED_SPEEDS)
            num_devices = res[0]
            for i in range(0, num_devices):
                if self._has_pump:
                    label = 'AIO port connected' if i == 0 else f'Fan port {i} connected'
                else:
                    label = f'Fan port {i+1} connected'

                status += [(label, res[i + 1] == 0x07, '')]

            # Get what temp sensors are connected
            for i, temp in enumerate(self._get_temps()):
                connected = temp is not None
                if self._has_pump:
                    label = 'Water temperature sensor' if i == 0 and self._has_pump else f'Temperature sensor {i}'
                else:
                    label = f'Temperature sensor {i+1}'

                status += [(label, connected, '')]

        return status

    def get_status(self, **kwargs):
        """Get all the fan speeds and temps"""
        status = []

        with self._wake_device_context():
            for i, speed in enumerate(self._get_speeds()):
                if self._has_pump:
                    label = 'Pump speed' if i == 0 else f'Fan speed {i}'
                else:
                    label = f'Fan speed {i+1}'

                status += [(label, speed, 'rpm')]

            for i, temp in enumerate(self._get_temps()):
                if temp is None:
                    continue

                if self._has_pump:
                    label = 'Water temperature' if i == 0 else f'Temperature {i}'
                else:
                    label = f'Temperature {i}'

                status += [(label, temp, '°C')]

        return status

    def set_color(self, channel, mode, colors, **kwargs):
        raise NotSupportedByDriver

    def set_speed_profile(self, channel, profile, **kwargs):
        channels = self._parse_channels(channel)

       # print(f"channels: {channels}")
       # print(list(profile))

        # Format the curve data
        fan_count = len(channels)
        curve_data = bytearray([0x00, 0x00, fan_count])
        for speed, temp in profile:
            curve_data.append(int(clamp(speed, 0, 100)))
            curve_data.append(int(clamp(temp, 0, 100)))

        with self._wake_device_context():
            # Set hardware speed mode
            res = self._read_data(_MODE_HW_SPEED_MODE, _DATA_TYPE_HW_SPEED_MODE)
            device_count = res[0]

            data = bytearray(res[0:device_count + 1])
            for chan in channels:
                data[chan + 1] = _FAN_MODE_CURVE_PERCENT
            self._write_data(_MODE_HW_SPEED_MODE, _DATA_TYPE_HW_SPEED_MODE, data)

            # Read in data and split by device
            res = self._read_data(_MODE_HW_CURVE_PERCENT, _DATA_TYPE_HW_CURVE_PERCENT)
            device_count = res[0]
            data_by_device = []
            i = 1
            for _ in range(0, device_count):
                print(i, res)
                count = res[i+1]
                start = i
                end = i + 4 * count + 2
                i = end
                data_by_device.append(res[start:end])

            # Modify the correct channels
            for data in data_by_device:
                channel_number = data[0] - 1
                if channel_number in channels:
                    # Find the index of the current channel in the list of channels
                    idx = channels.index(channel_number)
                    # Modify the speed and temp values for the channel
                    curve_data_idx = 2 + 2 * idx
                    data[curve_data_idx] = curve_data[curve_data_idx]
                    data[curve_data_idx + 1] = curve_data[curve_data_idx + 1]

            # Combine the modified data for each device into a single byte array
            out = bytes([device_count]) + b''.join(data_by_device)
            self._write_data(_MODE_HW_CURVE_PERCENT, _DATA_TYPE_HW_CURVE_PERCENT, out)

    def set_fixed_speed(self, channel, duty, **kwargs):
        channels = self._parse_channels(channel)

        with self._wake_device_context():
            # Set hardware speed mode
            res = self._read_data(_MODE_HW_SPEED_MODE, _DATA_TYPE_HW_SPEED_MODE)
            device_count = res[0]

            data = bytearray(res[0:device_count + 1])
            for chan in channels:
                data[chan + 1] = _FAN_MODE_FIXED_PERCENT
            self._write_data(_MODE_HW_SPEED_MODE, _DATA_TYPE_HW_SPEED_MODE, data)

            # Set speed
            res = self._read_data(_MODE_HW_FIXED_PERCENT, _DATA_TYPE_HW_FIXED_PERCENT)
            device_count = res[0]
            data = bytearray(res[0:device_count * 2 + 1])
            duty_le = int.to_bytes(clamp(duty, 0, 100), length=2, byteorder="little", signed=False)
            for chan in channels:
                i = chan * 2 + 1
                data[i: i + 2] = duty_le  # Update the device speed
            self._write_data(_MODE_HW_FIXED_PERCENT, _DATA_TYPE_HW_FIXED_PERCENT, data)

    @classmethod
    def probe(cls, handle, **kwargs):
        """Ensure we get the right interface"""

        if handle.hidinfo['interface_number'] != _INTERFACE_NUMBER:
            return

        yield from super().probe(handle, **kwargs)

    def _get_speeds(self):
        speeds = []

        res = self._read_data(_MODE_GET_SPEEDS, _DATA_TYPE_SPEEDS)

        num_speeds = res[0]
        speeds_data = res[1:1 + num_speeds * 2]
        for i in range(0, num_speeds):
            speeds.append(u16le_from(speeds_data, offset=i * 2))

        return speeds

    def _get_temps(self):
        temps = []

        res = self._read_data(_MODE_GET_TEMPS, _DATA_TYPE_TEMPS)

        num_temps = res[0]
        temp_data = res[1:1 + num_temps * 3]
        for i in range(0, num_temps):
            connected = temp_data[i * 3] == 0x00
            if connected:
                temps.append(u16le_from(temp_data, offset=i * 3 + 1) / 10)
            else:
                temps.append(None)

        return temps

    def _read_data(self, mode, data_type):
        self._send_command(_CMD_OPEN_ENDPOINT, mode)
        raw_data = self._send_command(_CMD_READ)
        self._send_command(_CMD_CLOSE_ENDPOINT)
        if tuple(raw_data[3:5]) != data_type:
            raise ExpectationNotMet('device returned incorrect data type')

        return raw_data[5:]

    def _send_command(self, command, data=()):
        # self.device.write expects buf[0] to be the report number or 0 if not used
        buf = bytearray(_REPORT_LENGTH + 1)

        # buf[1] when going out is always 08
        buf[1] = 0x08

        # Indexes for the buffer
        cmd_start = 2
        data_start = cmd_start + len(command)
        data_end = data_start + len(data)

        # Fill in the buffer
        buf[cmd_start:data_start] = command
        buf[data_start:data_end] = data

        self.device.clear_enqueued_reports()
        self.device.write(buf)

        res = self.device.read(_RESPONSE_LENGTH)
        while res[0] != 0x00:
            res = self.device.read(_RESPONSE_LENGTH)        
        buf = bytes(res)
        assert buf[1] == command[0], 'response does not match command'
        return buf

    @contextmanager
    def _wake_device_context(self):
        try:
            self._send_command(_CMD_WAKE)
            yield
        finally:
            self._send_command(_CMD_SLEEP)

    def _write_data(self, mode, data_type, data):
        self._read_data(mode, data_type)  # Will ensure we are writing the correct data type to avoid breakage

        self._send_command(_CMD_OPEN_ENDPOINT, mode)

        buf = bytearray(len(data) + len(data_type) + 4)
        buf[0: 2] = int.to_bytes(len(data) + 2, length=2, byteorder="little", signed=False)
        buf[4: 4 + len(data_type)] = data_type
        buf[4 + len(data_type):] = data

        self._send_command(_CMD_WRITE, buf)
        self._send_command(_CMD_CLOSE_ENDPOINT)

    def _fan_to_channel(self, fan):
        if self._has_pump:
            return fan
        else:
            # On devices without a pump, channel 0 is fan 1
            return fan - 1

    def _parse_channels(self, channel):
        if self._has_pump and channel == 'pump':
            return [0]
        elif channel == "fans":
            return [self._fan_to_channel(x) for x in range(1, _FAN_COUNT + 1)]
        elif channel.startswith("fan") and channel[3:].isnumeric() and 0 < int(channel[3:]) <= _FAN_COUNT:
            return [self._fan_to_channel(int(channel[3:]))]
        else:
            fan_names = ['fan' + str(i) for i in range(1, _FAN_COUNT + 1)]
            fan_names_part = '", "'.join(fan_names)
            if self._has_pump:
                fan_names.insert(0, "pump")
            raise ValueError(f'unknown channel, should be one of: "{fan_names_part}" or "fans"')

    def set_screen(self, channel, mode, value, **kwargs):
        """Not supported by this device."""
        raise NotSupportedByDevice`

how wrong was i ? lol

**Comment by Albinoman887** [comment]
> Progress report: either I'm not seeing something obvious, or the fact that v2 firmware is limited to 96 bytes of response means that the `_MODE_HW_CURVE_PERCENT` command response will always be truncated and unusable. Reverting `RESPONSE_LENGTH` to 1024 doesn't seem to help.
> 
> I don't have Wireshark experience, but I'll try to get Windows onto that machine and see what the vendor driver is doing there (unless I'm missing something obvious, that is).

did you ever mess around with this more you u set it down for now?

**Comment by jonasmalacofilho** [comment]
@Albinoman887, please use either diffs (for small changes) or PRs (for small or large changes) instead of just pasting the whole module with no indication of what exactly was changed.

Also, please clearly indicate when changes are generated by GPT (or similar predictive text tools), as it seems to be the case here from your commit history and branch names. You need to communicate that there may have been no thought whatsoever behind some of the changes, otherwise we might waste a lot of time trying to make sense of something thinking "oh, but they probably had a good reason to do it this way".

**Comment by Albinoman887** [comment]
> @Albinoman887, please use either diffs (for small changes) or PRs (for small or large changes) instead of just pasting the whole module with no indication of what exactly was changed.
> 
> Also, please clearly indicate when changes are generated by GPT (or similar predictive text tools), as it seems to be the case here from your commit history and branch names. You need to communicate that there may have been no thought whatsoever behind some of the changes, otherwise we might waste a lot of time trying to make sense of something thinking "oh, but they probably had a good reason to do it this way".

Ok I'l get right on that. I just wasn't sure how active the project was and didn't want to waste too much time if no one was going to reply. but in general its just the "set_speed_profile" method that GPT had any involvment though.

**Comment by paskalll** [comment]
Nothing new here?

I am a but afraid that my pump runs at 100% all the time 😅

It sounds like. Need to do the workaround again to set fix values but don't know what are good values to go for?

Thanks.

**Pull request closed without merging**
