### PR TITLE
Support for Corsair iCUE H150i RGB ELITE

### PR DESCRIPTION
**Pull request by jonasmalacofilho**
Add support for the Corsair iCUE H150i RGB ELITE, based on #557.

While this has been attempted in the past, [unsuccessfully](https://github.com/liquidctl/liquidctl/issues/498#issuecomment-1259804020), we never knew exactly why that happened. It's possible that in the meantime the issue has been solved (by other changes to the driver). It is also possible that at that time the properties weren't filled in correctly (e.g. the value of `fan_leds`). So let's try it again.

@sdns575, can you give this a try?

Fixes: #498

---

Checklist:

- [x] Adhere to the [development process]
- [x] Conform to the [style guide]
- [ ] Verify that the changes work as expected on real hardware (@sdns575)
- [ ] Add automated tests cases
- [x] Verify that all (other) automated tests (still) pass
- [x] Update/add documentation
    - [x] README, with ["new/changed in" notes]
    - [x] applicable `docs/*guide.md` device guides, with ["new/changed in" notes]
    - [x] `liquidctl.8` Linux/Unix/Mac OS man page
    - [ ] protocol documentation in `docs/developer/protocol`
- [ ] Submit relevant data, scripts or dissectors to https://github.com/liquidctl/collected-device-data

New CLI flag?

- [ ] Adjust the completion scripts in `extra/completions/`

New device?

- [x] Regenerate `extra/linux/71-liquidctl.rules` (instructions in the file header)
- [x] Add entry to the README's supported device list with applicable notes (at least `e`) and `git` MRLV

New driver?

- [ ] Document the protocol in `docs/developer/protocol/`

[development process]: https://github.com/liquidctl/liquidctl/blob/main/docs/developer/process.md
[style guide]: https://github.com/liquidctl/liquidctl/blob/main/docs/developer/style-guide.md
["new/changed in" notes]: https://github.com/liquidctl/liquidctl/blob/main/docs/developer/process.md#newchanged-in-notes

### CODE REVIEW

**Comment by pigmej** [comment]
Corsair H170i Elite LCD works. I mean no LCD controls, but all others seem to be working fine.

```
Corsair Commander ST (experimental)
├── Pump speed           2324  rpm
├── Fan speed 1           853  rpm
├── Fan speed 2           850  rpm
├── Fan speed 3           818  rpm
├── Fan speed 4             0  rpm
├── Fan speed 5             0  rpm
├── Fan speed 6             0  rpm
└── Water temperature    30.7  °C
```

**Comment by jonasmalacofilho** [comment]
@pigmej are you by any chance on the wrong PR? If you really intended to comment here, can you please explain the relationship between the H170i Elite LCD and the code this PR changes?

**Comment by pigmej** [comment]
H150i and h170i are the same just radiator is bigger and fans are 3x140 instead of 3x120.

Therefore imho it's the same hardware.

**Comment by jonasmalacofilho** [comment]
@pigmej unfortunately things are more complicated than that, and the H170i Elite **LCD** and **Capellix** use a completely different protocol from the H150i Elite **RGB**. So you're commenting on a PR that changes a completely different driver.

**Comment by pigmej** [comment]
> @pigmej unfortunately things are more complicated than that, and the H170i Elite **LCD** and **Capellix** use a completely different protocol from the H150i Elite **RGB**. So you're commenting on a PR that changes a completely different driver.

ok, if it's different then ok. Sorry for the confusion then! Thought it's the same. Sorry @jonasmalacofilho

**Comment by kevinlieser** [comment]
Have the same hardware (H150i Elite, Product ID: 0x0c37, Vendor ID: 0x1b1c) as in #498 and uninstalled and installed via brew (macOS). Running version `liquidctl v1.12.1 (macOS-13.1-x86_64-i386-64bit)` tells me on `liquidctl list` exactly nothing – or am I missing anything?

**Comment by jonasmalacofilho** [comment]
@kevinlieser,

This PR is not part of v1.12.1.

**Comment by kevinlieser** [comment]
> @kevinlieser,
> 
> This PR is not part of v1.12.1.

Oh okay, the latest release was also 3 weeks ago – so I thought. Do I need to self compile it?

**Comment by jonasmalacofilho** [comment]
@kevinlieser,

You need to use/install this particular snapshot of the code because the code in this _open/unmerged_ PR hasn't yet made it to the `main` branch, from which releases are derived.

In this particular case, that's due to lack of testesting; see second paragraph of the PR description.

You can take a look at our readme for some guidance on how to install liquidctl from git or tarball sources. And the branch you want is `h150i-elite-rgb`.

**Comment by kevinlieser** [comment]
> @kevinlieser,
> 
> You need to use/install this particular snapshot of the code because the code in this _open/unmerged_ PR hasn't yet made it to the `main` branch, from which releases are derived.
> 
> In this particular case, that's due to lack of testing; see second paragraph of the PR description.
> 
> You can take a look at our readme for some guidance on how to install liquidctl from git or tarball sources. And the branch you want is `h150i-elite-rgb`.

Thanks @jonasmalacofilho

The commands work but cannot install it on macOS. But this is another issue and has nothing to do with the support for H150i.

`  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 475, in __init__
          _Distribution.__init__(
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py", line 904, in finalize_options
          ep(self)
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools_scm/integration.py", line 127, in infer_version
          _assign_version(dist, config)
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools_scm/integration.py", line 63, in _assign_version
          _version_missing(config)
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 108, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /Users/kevinlieser/Desktop/liquidctl-h150i-elite-rgb.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed`

**Comment by kevinlieser** [comment]
Works nice but cannot set pump speed.
`liquidctl --match corsair set pump speed 100`
`ERROR: Corsair iCUE H150i Elite RGB (experimental): unexpected error: ValueError("unknown channel, should be one of: 'fan', 'fan1', 'fan2', 'fan3'")`

**Comment by jonasmalacofilho** [comment]
@kevinlieser ,

No, as far as we know only a few predefined pump modes are available: https://github.com/liquidctl/liquidctl/blob/main/docs/corsair-platinum-pro-xt-guide.md

**Comment by itay-grudev** [comment]
I've been testing these changes. I have a `1b1c:0c37 Corsair H150iELITE`.

Is there a checklist you would like me to go through?

**Comment by jonasmalacofilho** [comment]
@itay-grudev,

> I've been testing these changes. I have a `1b1c:0c37 Corsair H150iELITE`.

I'm glad to read that.

> Is there a checklist you would like me to go through?

Can you check if all features described in the [device guide](https://github.com/liquidctl/liquidctl/blob/12ff90b60065c87b56bd9c9807eb5030b5a8ce19/docs/corsair-platinum-pro-xt-guide.md) indeed work?

Thanks!

**Pull request merged**
